### PR TITLE
Fix reflection errors during native execution

### PR DESCRIPTION
**Pull request by EvaristeGalois11**
Hi, after updating to the new version 1.34.0 I'm receiving this error running the native binary:

```
error: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
java.lang.LinkageError: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
        at com.google.googlejavaformat.java.Trees.getEndPosMethodHandle(Trees.java:278)
        at com.google.googlejavaformat.java.Trees.<clinit>(Trees.java:251)
        at com.google.googlejavaformat.java.Formatter.format(Formatter.java:104)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:214)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:188)
        at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:75)
        at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:29)
        at java.base@25.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:328)
        at java.base@25.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base@25.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:328)
        at java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base@25.0.2/java.lang.Thread.runWith(Thread.java:1487)
        at java.base@25.0.2/java.lang.Thread.run(Thread.java:1474)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
Caused by: java.lang.NoSuchMethodException: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
        at java.base@25.0.2/java.lang.invoke.MemberName.makeAccessException(MemberName.java:910)
        at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
        at java.base@25.0.2/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3591)
        at java.base@25.0.2/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2610)
        at com.google.googlejavaformat.java.Trees.getEndPosMethodHandle(Trees.java:269)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.tree.JCTree.getEndPosition(com.sun.tools.javac.tree.EndPosTable)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:352)
        at java.base@25.0.2/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:208)
        at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:120)
        at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
        ... 18 more

```

It's caused by https://github.com/google/google-java-format/commit/4a15b1b9a4063a8ec2958ba3fc0924d1be046b93 that introduced new reflection invocations that the native build process isn't able to pick up.
Following [this guide](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/) I generated an updated config file to fix the problem. The config file name changed in Graal 23, but it's only used during build time so it shouldn't matter that much.

With this fix everything works fine (at least for my case :grin:).

### CODE REVIEW

**Review by cushon — APPROVED** [review]

**Comment by cushon** [comment]
> In my case, with java 25.0.1 (macOS x86_64) in addition to that change, I had to add `--initialize-at-build-time=com.google.googlejavaformat.java.Trees`

Hmm, it works for me with 25.0.2+10 on mac arm64 with just this change. There were also some recent changes in f0a9748d045d54f3ebb78511bafc358cea6feb31 to the use of reflection here that may affect graal.

@natros could you trying 25.0.2 and also the google-java-format changes from f0a9748d045d54f3ebb78511bafc358cea6feb31, and see if `--initialize-at-build-time=com.google.googlejavaformat.java.Trees` is still necessary for you?

**Comment by cushon** [comment]
I made a new release with these changes: https://github.com/google/google-java-format/releases/tag/v1.34.1

> I'm afraid I don't have a mac system so I can't help testing on it 😅
> 
> Also @cushon do you think it could be a good idea to add a simple smoke test for formatting with graal? Because currently https://github.com/google/google-java-format/blob/master/util/test-native.sh only tests for the basic help output and nothing more. It should be pretty easy to add a `google-java-format HelloWorld.java` or something like that. I can do it in this pr or open another one to keep them separate, just let me know what you think it's preferable.

I just saw this--yes, that sounds like an excellent idea, if you'd be willing to put a PR together that would be great.

**Comment by amengslank56-wq** [comment]
> Halo, setelah memperbarui ke versi baru 1.34.0, saya menerima kesalahan ini saat menjalankan binary native:
> 
> ```
> error: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
> java.lang.LinkageError: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
>         at com.google.googlejavaformat.java.Trees.getEndPosMethodHandle(Trees.java:278)
>         at com.google.googlejavaformat.java.Trees.<clinit>(Trees.java:251)
>         at com.google.googlejavaformat.java.Formatter.format(Formatter.java:104)
>         at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:214)
>         at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:188)
>         at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:75)
>         at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:29)
>         at java.base@25.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:328)
>         at java.base@25.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
>         at java.base@25.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:328)
>         at java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
>         at java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
>         at java.base@25.0.2/java.lang.Thread.runWith(Thread.java:1487)
>         at java.base@25.0.2/java.lang.Thread.run(Thread.java:1474)
>         at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
>         at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
> Caused by: java.lang.NoSuchMethodException: no such method: com.sun.tools.javac.tree.JCTree.getEndPosition(EndPosTable)int/invokeVirtual
>         at java.base@25.0.2/java.lang.invoke.MemberName.makeAccessException(MemberName.java:910)
>         at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
>         at java.base@25.0.2/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3591)
>         at java.base@25.0.2/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2610)
>         at com.google.googlejavaformat.java.Trees.getEndPosMethodHandle(Trees.java:269)
>         ... 15 more
> Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.tree.JCTree.getEndPosition(com.sun.tools.javac.tree.EndPosTable)
>         at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:352)
>         at java.base@25.0.2/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:208)
>         at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:120)
>         at java.base@25.0.2/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
>         ... 18 more
> ```
> 
> Masalah ini disebabkan oleh [4a15b1b](https://github.com/google/google-java-format/commit/4a15b1b9a4063a8ec2958ba3fc0924d1be046b93) yang memperkenalkan pemanggilan refleksi baru yang tidak dapat ditangkap oleh proses build native. Mengikuti [panduan ini](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/) , saya membuat file konfigurasi yang diperbarui untuk memperbaiki masalah tersebut. Nama file konfigurasi berubah di Graal 23, tetapi hanya digunakan selama waktu build sehingga seharusnya tidak terlalu berpengaruh.
> 
> Dengan perbaikan ini, semuanya berfungsi dengan baik (setidaknya untuk kasus saya 😁).

https://github.com/google/google-java-format/pull/1327#issue-3893622715
